### ISSUE TITLE
2dstructure cell in exported cif and visualization

### ISSUE THREAD

**Issue by eimrek** [materialscloud-org/tools-optimade-client#106]
The 2dstructures, that have `dimension_types": [ 1, 1, 0],` don't handle cells correctly: it's not visualized and not included in the downloaded files (e.g. cifs).

See e.g.

![image](https://user-images.githubusercontent.com/8721264/171027012-dd72cf61-a066-461c-a9ad-11805e72f297.png)

**Comment by unkcpz** [comment]
This will be resolved by https://github.com/Materials-Consortia/optimade-python-tools/issues/1212

**Comment by CasperWA** [comment]
I think CasperWA/voila-optimade-client#432 should solve this? Maybe you could try to checkout that PR branch and check to confirm?
