### ISSUE TITLE
slow performance while loading on dokku

### ISSUE THREAD

**Issue by ltalirz** [materialscloud-org/tools-optimade-client#11]
@CasperWA you mentioned that sometimes the app is slow to load on the dokku instance (e.g. optimadeclient.matcloud.xyz ).
Can you be a bit more specific so that we can have a look into this?

**Comment by CasperWA** [comment]
It's difficult at the moment for me to be specific, but the main difference between the dokku instance of the application and the "local" instance (deployed on the `dev-tools` server through `repo2docker`) is the missing initial spinner that shows up immediately for the "local" case, while it's simply waiting for a connection with a blank canvas for a time in the dokku instance and then briefly flashes the spinner before running the actual notebook.

The running of the notebook takes the same amount of time for each host, it's more about the time spent leading up to it.

That's unfortunately how specific I can get.

**Comment by CasperWA** [comment]
So it seems `materialscloud.io` properly shows the spinner now, but `matcloud.xyz` does not?

**Comment by ltalirz** [comment]
> So it seems `materialscloud.io` properly shows the spinner now, but `matcloud.xyz` does not?

Right - I deployed the fix manually on materialscloud.io, I still need to automate it (unfortunately, this means we need to store for each app whether it is a voila app or not; I'm still somehow hoping we can avoid this).

**Comment by CasperWA** [comment]
> > So it seems `materialscloud.io` properly shows the spinner now, but `matcloud.xyz` does not?
> 
> Right - I deployed the fix manually on materialscloud.io, I still need to automate it (unfortunately, this means we need to store for each app whether it is a voila app or not; I'm still somehow hoping we can avoid this).

Could you apply the fix no matter what kind of app it is? I.e., will other kind of apps be affected?

**Comment by CasperWA** [comment]
Do you know how much data is buffered initially?
We could then try to fill up this buffer from the side of the template before anything else is loaded?

**Comment by ltalirz** [comment]
> Do you know how much data is buffered initially?

16K I believe

> We could then try to fill up this buffer from the side of the template before anything else is loaded?

I've automated the configuration now
https://optimadeclient.matcloud.xyz/

For the time being one needs to specify an extra key for voila apps - if they ever switch to another mode of showing the spinner, we can remove it again
