### ISSUE TITLE
deploy CI push to dev and production server 

### ISSUE THREAD

**Issue by unkcpz** [materialscloud-org/tools-optimade-client#117]
To me, the deploy workflow makes more sense that the dev server is for test manually and the production server is updated and deployed by the PR merged in this repository. 
In this way, we have more flexibility to test with dev server by manually pushing. The production server is updated only by PR which is more robust and error trackable.

Any thoughts? @CasperWA @eimrek

**Comment by unkcpz** [comment]
Faild when push to dokku server. I don't have permission to change secret of this repo, have to wait for Casper, he is on holiday.

**Comment by unkcpz** [comment]
It now works with the newly set ssh key without jump host needed. I'll keep this issue open to confirm with @CasperWA if other action secrets can be removed. Now only `SSH_KEY_DOKKU` and `SSH_KNOWN_HOST_DOKKU` are used.

**Comment by CasperWA** [comment]
> It now works with the newly set ssh key without jump host needed. I'll keep this issue open to confirm with @CasperWA if other action secrets can be removed. Now only `SSH_KEY_DOKKU` and `SSH_KNOWN_HOST_DOKKU` are used.

Sounds good - if you don't need the old repository secrets, please just remove them :)

**Comment by unkcpz** [comment]
Thanks! I removed them and only keeps two the `secrets.SSH_KEY_DOKKU` and `secrets.SSH_KNOWN_HOST_DOKKU`
