### ISSUE TITLE
Unsupported Python version

### ISSUE THREAD

**Issue by CasperWA** [materialscloud-org/tools-optimade-client#129]
See [this CD run](https://github.com/materialscloud-org/tools-optimade-client/actions/runs/3838335070/jobs/6534669149#step:4:17).

The error message is quite confusing, as the referenced list of valid versions includes Python 3.8.16.

**Comment by unkcpz** [comment]
@dou-du update the dokku and herokuish version last month, I think the image is now changed and that cause the unsupported. 
@dou-du Which python version in runtime configure should we use?

**Comment by dou-du** [comment]
https://devcenter.heroku.com/articles/python-support

python-3.11.1 on all [supported stacks](https://devcenter.heroku.com/articles/stack#stack-support-details)
python-3.10.9 on all [supported stacks](https://devcenter.heroku.com/articles/stack#stack-support-details) (recommended)
python-3.9.16 on all [supported stacks](https://devcenter.heroku.com/articles/stack#stack-support-details)
python-3.8.16 on Heroku-18 and Heroku-20 only
python-3.7.16 on Heroku-18 and Heroku-20 only

Is it posibble to upgrade python to 3.9.16?

**Comment by CasperWA** [comment]
I can open the PR and you can then merge and test?

**Comment by unkcpz** [comment]
No problem, I'll test it and merge it. Thanks for the PR.

**Comment by unkcpz** [comment]
Since #130 merged, this issue can be closed.
