### ISSUE TITLE
Deployment not working

### ISSUE THREAD

**Issue by CasperWA** [materialscloud-org/tools-optimade-client#87]
It seems the standard deployment is not working any more (see [this job](https://github.com/materialscloud-org/tools-optimade-client/runs/4346496838?check_suite_focus=true)).

Are there any updates on this or resources I can read to figure out how to update this @elsapassaro?

**Comment by elsapassaro** [comment]
Sorry I don't know, pinging @dou-du who is managing the dokku servers and might have more info

**Comment by CasperWA** [comment]
It seems it's still the case (not working) [latest CD job](https://github.com/materialscloud-org/tools-optimade-client/runs/4378443454?check_suite_focus=true).

It might be that the host URL has changed?

**Comment by CasperWA** [comment]
This has been resolved from the side of connecting via SINTEF, i.e., this issue now represents updating the CD workflow from GitHub to work via the SINTEF network.

**Comment by unkcpz** [comment]
I think this one is resolved.
